version: '3.8'
services:
  db: 
    image: 'postgres:12'
    ports: 
      - '54320:5432'
    volumes:
      - ./db/data/dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next_goat_dev_db